### ISSUE TITLE
rysk cli command throws ImportError

### ISSUE THREAD

**Issue by StuartFyfe** [8ball030/rysk_explorations#27]
Python 3.11.3 (main, Apr  7 2023, 20:13:31) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin

Steps to reproduce:

```
poetry init
pip install rysk-client
rysk
```

```
ImportError: cannot import name 'getargspec' from 'inspect'
```

**Comment by 8ball030** [comment]
@StuartFyfe 
I have bumped a new version can you check if the error still persists?

**Comment by 8ball030** [comment]
Should now be supporting python3.11

**Comment by StuartFyfe** [comment]
I've just updated to `0.1.9` and I'm now getting:
```
Traceback (most recent call last):
  File "/Users/stuartfyfe/Library/Caches/pypoetry/virtualenvs/rysk-_kasV_qU-py3.11/bin/rysk", line 5, in <module>
    from rysk_client.cli import cli
  File "/Users/stuartfyfe/Library/Caches/pypoetry/virtualenvs/rysk-_kasV_qU-py3.11/lib/python3.11/site-packages/rysk_client/cli.py", line 9, in <module>
    from rysk_client.client import RyskClient
  File "/Users/stuartfyfe/Library/Caches/pypoetry/virtualenvs/rysk-_kasV_qU-py3.11/lib/python3.11/site-packages/rysk_client/client.py", line 20, in <module>
    from rysk_client.web3_client import Web3Client
  File "/Users/stuartfyfe/Library/Caches/pypoetry/virtualenvs/rysk-_kasV_qU-py3.11/lib/python3.11/site-packages/rysk_client/web3_client.py", line 10, in <module>
    import websocket
ModuleNotFoundError: No module named 'websocket'
```

**Comment by 8ball030** [comment]
@StuartFyfe This should be resolved now.
https://github.com/8ball030/rysk_explorations/blob/5aa389f285aeb393c016cc6b8f92be8105d0795e/pyproject.toml#L16C1-L16C28
